services:
  - type: worker
    name: surfcheck_bot
    env: python
    region: oregon
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
    autoDeploy: true
    envVars:
      - key: BOT_TOKEN
        sync: false