services:
  - type: web
    name: surfcheck_bot
    env: python
    plan: free
    pythonVersion: 3.10
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
    autoDeploy: true
    envVars:
      - key: BOT_TOKEN
        sync: false
