name: Deploy to Fly.io

on:
  push:
    branches:
      - main  # ou 'master', dependendo do seu repositório

jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Instalar Fly CLI
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy no Fly.io
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: flyctl deploy --remote-only
